### ISSUE TITLE
Replace the line without having the information being printed one next to the other

### ISSUE THREAD

**Issue by rizzini** [Zren/plasma-applet-commandoutput#37]
Is it possible to replace the last output with, for example:
```
for i in {10..1}; do printf "Counting down: $i\r" && sleep 1; done
```

**Comment by Zren** [comment]
More Discussion: https://old.reddit.com/r/kde/comments/yaofwl/is_there_any_other_widget_that_prints_the_output/

Since the widget is basically:

```bash
output=`cmd 1234`
echo "$output"
```

It's not really possible to do this. That command would take 10 seconds to run, then print "Counting down: 1" even if I made `\r` delete the last line in the output.

**Comment by rizzini** [comment]
Thanks, man.
